import { NextPage, GetStaticProps, GetStaticPaths } from 'next'
import { Button, Card, CardActions, CardContent, CardHeader, CardMedia, Typography } from '@material-ui/core'
import Head from 'next/head'

const Page404: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Página não encontrada</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Typography
        component="h1"
        variant="h4"
        align='center'
        color="textPrimary"
        gutterBottom
      >
        404 - Página não encontrada
      </Typography>
    </div>
  )
}

export default Page404